version: '2'

services:
  bunkbot:
    image: starbunk/bunkbot
    container_name: bunkbot
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - docker.env
  musicbot:
    image: craumix/jmusicbot
    container_name: dj-cova
    restart: unless-stopped
    volumes:
     - ~/docker/starbunk/config:/jmb/config/
