version: '2'

services:
  bunkbot:
    image: localhost:5000/starbunk/bunkbot
    container_name: bunk-bot
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - docker.env
  musicbot:
    image: localhost:5000/starbunk/musicbot
    container_name: dj-cova
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile.Music
