version: '2'

services:
  registry:
    image: registry:latest
    ports:
      - "5000:5000"
  registry-frontend:
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - "8080:80"
    environment:
      - ENV_DOCKER_REGISTRY_HOST="localhost"

  bunkbot:
    image: localhost:5000/starbunk/bunkbot
    container_name: bunk-bot
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - docker.env
  musicbot:
    image: localhost:5000/starbunk/musicbot
    container_name: dj-cova
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile.Music
