version: '2'

services:
  bunkbot:
    # image: covadax/bunkbot:latest
    container_name: bunk-bot
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    env_file:
      - docker.env
  musicbot:
    # image: covadax/djcova:latest
    container_name: dj-cova
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile.Music
    network_mode: "host"
    env_file:
      - docker.env
