version: '2'

services:
  bunkbot:
    image: starbunk/bunkbot:latest
    container_name: bunk-bot
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - docker.env
  musicbot:
    image: starbunk/musicbot:latest
    container_name: dj-cova
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile.Music
